steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild-app:$SHORT_SHA', '.' ]
images:
- 'us-east4-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild-app:$SHORT_SHA'
options:
  substitution_option: 'ALLOW_LOOSE'
